# Generated by Django 3.1.1 on 2020-10-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_document_number',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
