# Generated by Django 3.1.1 on 2020-10-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_identity_document_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('create_date',)},
        ),
    ]
