# Generated by Django 3.1.1 on 2020-10-11 05:30
from datetime import datetime

from django.db import migrations


def import_example_campaigns_and_options(apps, schema_editor):
    PollCampaign = apps.get_model('poll', 'PollCampaign')
    campaign_1 = PollCampaign.objects.create(
        title_en='Who is the best NBA player in history?',
        title_zh='',
        effective_from=datetime(2019, 1, 1).astimezone(),
        effective_to=datetime(2019, 1, 31).astimezone(),
    )
    campaign_1.options.create(name_en='Michael Jordan', name_zh='')
    campaign_1.options.create(name_en='Kobe Bryant', name_zh='')
    campaign_1.options.create(name_en='Lebron James', name_zh='')
    campaign_1.options.create(name_en='Stephen Curry', name_zh='')

    campaign_2 = PollCampaign.objects.create(
        title_en='Which HK CEO candidate do you preferred?',
        title_zh='',
        effective_from=datetime(2019, 1, 1).astimezone(),
        effective_to=datetime(2019, 1, 31).astimezone(),
    )
    campaign_2.options.create(name_en='Carrie Lam', name_zh='')
    campaign_2.options.create(name_en='John Tsang', name_zh='')
    campaign_2.options.create(name_en='Rebecca Ip', name_zh='')


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_example_campaigns_and_options)
    ]
