# Generated by Django 3.1.1 on 2020-10-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20201011_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('create_date',)},
        ),
        migrations.AlterModelOptions(
            name='pollcampaign',
            options={'ordering': ('create_date',)},
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'ordering': ('create_date',)},
        ),
    ]
